[server]
address = "127.0.0.1"
maxUploadSize = 500
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1FCB6B"
backgroundColor = "#F4F6F5"
secondaryBackgroundColor = "#EDF1EF"
textColor = "#151C1A"
font = "sans serif"
